Fix DFlash generation fail with max_tokens unset (#4532)
<!-- Keep your pull requests (PRs) as atomic as possible. That increases
the likelihood that an individual PR won't be stuck because of adjacent
problems, merge conflicts, or code review.
Your merged PR is going to appear in the automatically generated release
notes on GitHub. So the clearer the title the better. -->
## Description
<!-- Please include a summary of the change. Also include relevant
motivation and context. -->
Generation with DFlash fails when max_tokens unset due to an overflow
after adding the number of the assistant tokens to the `max_new_tokens`
which is already set to a maximum.

Reproduction of the bug:
```python
import openvino_genai as ov_genai

def text_streamer(subword: str) -> bool:
    print(subword, end="", flush=True)
    return False

model_path = "models/gemma-4-31b-it-int4-ov"
draft_model_path = "models/gemma-4-31b-it-dflash-int4-ov"
device = "GPU"
properties = {}
properties["draft_model"] = ov_genai.draft_model(draft_model_path, device)
scheduler_config = ov_genai.SchedulerConfig()
scheduler_config.enable_prefix_caching = False
properties["scheduler_config"] = scheduler_config
pipe = ov_genai.VLMPipeline(model_path, device, **properties)
config = ov_genai.GenerationConfig()
config.do_sample = False
pipe.generate("Why the sky is blue?", generation_config=config, streamer=text_streamer)
print()
```

Before fix:
```
TheTraceback (most recent call last):
  File "/home/sdp/benchmark-ov-qwen3.5/error_repro.py", line 22, in <module>
    pipe.generate("Why the sky is blue?", generation_config=config, streamer=text_streamer)
RuntimeError: Check 'num_running_sequences == 1' failed at src/cpp/src/sampling/sampler.cpp:1503
```

After fix:
```
The sky is blue because of a phenomenon called **Rayleigh scattering**.

Here is the step-by-step explanation of how it works:

### 1. Sunlight is a mix of all colors
Although sunlight^C looks white to us, it is actually made up of all the colors of the rainbow (red, orange, yellow, green, blue, indigo, and violet). Each of these colors travels as a different **wavelength**.
*   **Red light** has long, lazy waves.
*   **Blue and violet light** have short, choppy waves.
...
```


<!-- Jira ticket number (e.g., 123). Delete if there's no ticket. -->
[CVS-195648](https://jira.devtools.intel.com/browse/CVS-195648)


## Checklist:
- [x] This PR follows [GenAI Contributing
guidelines](https://github.com/openvinotoolkit/openvino.genai?tab=contributing-ov-file#contributing).
<!-- Always follow them. If there are deviations, explain what and why.
-->
- [x] <!-- (or N/A) --> Tests have been updated or added to cover the
new code. <!-- Specify exactly which tests were added or updated. If the
change isn't maintenance related, update the tests at
https://github.com/openvinotoolkit/openvino.genai/tree/master/tests or
explain in the description why the tests don't need an update. -->
- [x] <!-- (or N/A) --> This PR fully addresses the ticket. <!--- If
not, explain clearly what is covered and what is not. If follow-up pull
requests are needed, specify in the description. -->
- [ ] <!-- (or N/A) --> I have made corresponding changes to the
documentation. <!-- Run
github.com/\<username>/openvino.genai/actions/workflows/deploy_gh_pages.yml
on your fork with your branch as a parameter to deploy a test version
with the updated content. Replace this comment with the link to the
built docs. If the documentation is updated in a separate PR, clearly
specify it. -->

---------

Co-authored-by: Artur Paniukov <artur.paniukov@intel.com>