fix(python): Remove incompatible keep_alive from def_readwrite in GenerationConfig (#3915)
## Description

The `py::keep_alive<1, 2>()` policy is no longer supported with
pybind11's `def_readwrite()` method
([link](https://github.com/pybind/pybind11/pull/5533)), causing a static
assertion failure during compilation. This policy is unnecessary as
pybind11 automatically handles lifetime management for `def_readwrite`
attributes.

This is similar to the error fixed by this PR in OpenVINO:
https://github.com/openvinotoolkit/openvino/pull/34468

I've tested that this fixes compatibility with pybind11 when building
Python bindings for OpenVINO GenAI 2026.1.0.0.

To reproduce the error (building environment: Ubuntu 24.04), build
OpenVINO GenAI as an extra module:

```
git clone --branch 2026.1.0 --recursive https://github.com/openvinotoolkit/openvino.git
git clone --branch 2026.1.0.0 --recursive https://github.com/openvinotoolkit/openvino.genai.git
cmake   -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DENABLE_PYTHON=ON   -DPython3_EXECUTABLE=/usr/bin/python3.12   -DOPENVINO_EXTRA_MODULES=$(pwd)/openvino.genai   -DCPACK_ARCHIVE_COMPONENT_INSTALL=OFF   -S ./openvino   -B ./build
cmake --build ./build -j
.
.
In file included from /home/ubuntu/openvino-genai-python/openvino.genai/src/python/py_generation_config.cpp:5:
/home/ubuntu/openvino-genai-python/openvino/src/bindings/python/thirdparty/pybind11/include/pybind11/pybind11.h: In instantiation of ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def_property_static(const char*, const pybind11::cpp_function&, const pybind11::cpp_function&, const Extra& ...) [with Extra = {pybind11::is_method, pybind11::return_value_policy, pybind11::keep_alive<1, 2>}; type_ = ov::genai::GenerationConfig; options = {}]’:
/home/ubuntu/openvino-genai-python/openvino/src/bindings/python/thirdparty/pybind11/include/pybind11/pybind11.h:2438:35:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def_property(const char*, const pybind11::cpp_function&, const pybind11::cpp_function&, const Extra& ...) [with Extra = {pybind11::return_value_policy, pybind11::keep_alive<1, 2>}; type_ = ov::genai::GenerationConfig; options = {}]’
/home/ubuntu/openvino-genai-python/openvino/src/bindings/python/thirdparty/pybind11/include/pybind11/pybind11.h:2347:21:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def_readwrite(const char*, D C::*, const Extra& ...) [with C = ov::genai::GenerationConfig; D = std::vector<std::shared_ptr<ov::genai::Parser> >; Extra = {pybind11::keep_alive<1, 2>}; type_ = ov::genai::GenerationConfig; options = {}]’
/home/ubuntu/openvino-genai-python/openvino.genai/src/python/py_generation_config.cpp:450:23:   required from here
/home/ubuntu/openvino-genai-python/openvino/src/bindings/python/thirdparty/pybind11/include/pybind11/pybind11.h:2462:25: error: static assertion failed: def_property family does not currently support keep_alive. Use a py::cpp_function instead.
 2462 |         static_assert(0 == detail::constexpr_sum(detail::is_keep_alive<Extra>::value...),
      |                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/openvino-genai-python/openvino/src/bindings/python/thirdparty/pybind11/include/pybind11/pybind11.h:2462:25: note: the comparison reduces to ‘(0 == 1)’
gmake[2]: *** [build-modules/openvino.genai/src/python/CMakeFiles/py_openvino_genai.dir/build.make:104: build-modules/openvino.genai/src/python/CMakeFiles/py_openvino_genai.dir/py_generation_config.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:9712: build-modules/openvino.genai/src/python/CMakeFiles/py_openvino_genai.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```



## Checklist:
- [x] This PR follows [GenAI Contributing
guidelines](https://github.com/openvinotoolkit/openvino.genai?tab=contributing-ov-file#contributing).
<!-- Always follow them. If there are deviations, explain what and why.
-->
- [ ] Tests have been updated or added to cover the new code. <!--
Specify exactly which tests were added or updated. If the change isn't
maintenance related, update the tests at
https://github.com/openvinotoolkit/openvino.genai/tree/master/tests or
explain in the description why the tests don't need an update. -->
- [ ] This PR fully addresses the ticket. <!--- If not, explain clearly
what is covered and what is not. If follow-up pull requests are needed,
specify in the description. -->
- [ ] I have made corresponding changes to the documentation. <!-- Run
github.com/\<username>/openvino.genai/actions/workflows/deploy_gh_pages.yml
on your fork with your branch as a parameter to deploy a test version
with the updated content. Replace this comment with the link to the
built docs. If the documentation is updated in a separate PR, clearly
specify it. -->

Co-authored-by: Pavel Esir <pavel.esir@gmail.com>
Co-authored-by: Alexander Suvorov <alexander.suvorov@intel.com>