hook supports transformers 4.55.0 (#2776)
Fix hook error, while the transformers updated to 4.55.0
[ ERROR ] An exception occurred
[ INFO ] Traceback (most recent call last):
File
"/home/build/jenkins_home/workspace/test-llm-model-imp/openvino.genai/tools/llm_bench/benchmark.py",
line 290, in main
iter_data_list, pretrain_time, iter_timestamp =
CASE_TO_BENCH[model_args['use_case']](
File
"/home/build/jenkins_home/workspace/test-llm-model-imp/openvino.genai/tools/llm_bench/task/visual_language_generation.py",
line 308, in run_visual_language_generation_benchmark
model, processor, pretrain_time, bench_hook, use_genai =
FW_UTILS[framework].create_image_text_gen_model(model_path, device,
mem_consumption, **args)
File
"/home/build/jenkins_home/workspace/test-llm-model-imp/openvino.genai/tools/llm_bench/llm_bench_utils/ov_utils.py",
line 819, in create_image_text_gen_model
    bench_hook = get_bench_hook(kwargs['num_beams'], ov_model)
File
"/home/build/jenkins_home/workspace/test-llm-model-imp/openvino.genai/tools/llm_bench/llm_bench_utils/hook_common.py",
line 24, in get_bench_hook
    import llm_bench_utils.hook_beam_search
File
"/home/build/jenkins_home/workspace/test-llm-model-imp/openvino.genai/tools/llm_bench/llm_bench_utils/hook_beam_search.py",
line 17, in <module>
import llm_bench_utils.llm_hook_beam_search.hook_beam_search_v52 as
hook_beam_search_v52
File
"/home/build/jenkins_home/workspace/test-llm-model-imp/openvino.genai/tools/llm_bench/llm_bench_utils/llm_hook_beam_search/hook_beam_search_v52.py",
line 16, in <module>
    from transformers.generation.utils import (
ImportError: cannot import name '_split_model_inputs' from
'transformers.generation.utils'
(/home/build/jenkins_home/workspace/test-llm-model-imp/python-env/lib/python3.10/site-packages/transformers/generation/utils.py)