[Tests] [Samples] Upgrade transformers version in tests (#4395)
<!-- Keep your pull requests (PRs) as atomic as possible. That increases
the likelihood that an individual PR won't be stuck because of adjacent
problems, merge conflicts, or code review.
Your merged PR is going to appear in the automatically generated release
notes on GitHub. So the clearer the title the better. -->
## Description
<!-- Please include a summary of the change. Also include relevant
motivation and context. -->

<!-- Jira ticket number (e.g., 123). Delete if there's no ticket. -->
[CVS-193004](https://jira.devtools.intel.com/browse/CVS-193004)

For now if any tests failed with transformers 5.5.4, I've pinned
transformers 5.0.0 back for them and left a comment with a ticket, as
the goal is to clear alerts from Trivy and Dependabot.
I've moved the errors found in
[CVS-194062](https://jira.devtools.intel.com/browse/CVS-194062) and
[CVS-194253](https://jira.devtools.intel.com/browse/CVS-194253), so we
can fix them after we clear the alerts.

Other workarounds:
- The dependency_review exception is for:

```
Run actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
...
  samples/export-requirements.txt » transformers@5.5.4 – Transformers save_pretrained path traversal allows arbitrary file writes through chat template names (high severity)
    ↪ https://github.com/advisories/GHSA-xrqw-3rrv-vx5w
  Error: Dependency review detected vulnerable packages.
  ``` 
It didn't fail before, because it is triggered on diff, and the last bump of transformers was before the scan was added.


## Checklist:
- [x] This PR follows [GenAI Contributing guidelines](https://github.com/openvinotoolkit/openvino.genai?tab=contributing-ov-file#contributing). <!-- Always follow them. If there are deviations, explain what and why. -->
- [x] <!-- (or N/A) --> Tests have been updated or added to cover the new code. <!-- Specify exactly which tests were added or updated. If the change isn't maintenance related, update the tests at https://github.com/openvinotoolkit/openvino.genai/tree/master/tests or explain in the description why the tests don't need an update. -->
- [x] <!-- (or N/A) --> This PR fully addresses the ticket. <!--- If not, explain clearly what is covered and what is not. If follow-up pull requests are needed, specify in the description. -->
- N/A <!-- (or N/A) --> I have made corresponding changes to the documentation. <!-- Run github.com/\<username>/openvino.genai/actions/workflows/deploy_gh_pages.yml on your fork with your branch as a parameter to deploy a test version with the updated content. Replace this comment with the link to the built docs. If the documentation is updated in a separate PR, clearly specify it. -->