[WWB] Remove use_flash_attention_2 argument for phi4mm (#2653)
### Reason for changes

After update to transformers 4.53 WWB on phi4 multimodal started to fail
with:
```
TypeError: Phi4MMForCausalLM.__init__() got an unexpected keyword argument 'use_flash_attention_2'
```

In this PR this argument is removed for this model. SDPA implementation
is manually set through config to "sdpa" anyway.